server:
  port: 8080


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crud
    username: postgres
    password: sksmstldhs


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.crud.study.domain
  configuration:
    map-underscore-to-camel-case: true